### ISSUE TITLE
🐛 [BUG] - Can't create roles in Auth0

### ISSUE THREAD

**Issue by ETCasual** [fgacyc/api#20]
### Description

Trying to create roles to `Auth0` via API doesnt work

### Reproduction Steps

```bash
1. Go to https://identity.development.fgacyc.com/docs#post-/pastoral-roles
2. Fill in the details
3. Click try
4. See error message
```

### Screenshots

<img width="772" alt="image" src="https://github.com/fgacyc/api/assets/68994115/cc4440eb-7353-425f-a6ea-c3d54081cf32">

### Logs

```bash
{
  "message": "Failed to create a role on Auth0"
}
```

### Environment

```markdown
Google Chrome Version 116.0.5845.141 (Official Build) (64-bit)
```

### Additional Info

_None._

**Comment by marcustut** [comment]
<img width="1024" alt="Screenshot 2023-09-04 at 12 47 17 PM" src="https://github.com/fgacyc/api/assets/59773847/713c523d-b7ef-45a0-acfd-7ca9009a7e0e">

The issue is simple, it is because we did not gave these permissions to our Identity API in Auth0 Dashboard.
